### ISSUE TITLE
Proposal to un-deprecate this crate

### ISSUE THREAD

**Issue by Qqwy** [Seeker14491/generic-arrayvec#1]
There is an important niche which this crate fills that using `ArrayVec` directly cannot do (in stable Rust): Make the array size dependent on a compile-time calculation.

Doing this currently in stable Rust still requires usage of `typenum`. At a point in the far future we might get [complex generic expressions in constants](https://github.com/rust-lang/rust/issues/76560) but for the time being this feature is nightly-only, unfinished and very experimental.

The motivating example, is that I am implementing a B+ tree, which I want to parameterize on the branching factor.

For internal nodes, the branching factor `M` should result in an array containing at most `2*M` pointers to children, and an array containing at most `2*M-1` keys to branch between them.
(For leaf nodes, there is an equal amount of keys and values (both are `2*M-1`)).
By constraining the array sizes this way, users only need to fill in a single generic parameter. Also, trying to build a tree with a branching factor of `0` is prevented at compile-time.

Specifying this kind of constraint in stable rust is only possible by using `typenum` (and quite frankly a lot of `where` bounds :sweat_smile:) and `GenericArrayVec`.

This is of course only one example, but there are many other datastructures that would benefit from this as well.

**Comment by Seeker14491** [comment]
Thanks for bringing this to my attention. I haven't really tried out const generics yet and wasn't aware of the limitations. I'll un-deprecate and make a new release. Unfortunately the `arrayvec` dependency will need to stay stuck on v0.5, as the API of the new versions don't let me implement this library.

**Comment by Seeker14491** [comment]
I've released v0.4.0.

**Comment by Qqwy** [comment]
Thank you very much!
